admins: []
forwards:
- source: -1001703590290
  dest:
  - -1001737045523
  offset: 1792
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
