admins: []
forwards:
- source: https://t.me/LecturioVideos2022
  dest:
  - -1001542123472
  offset: 150
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
