admins: []
forwards:
- source: -1001769389007
  dest:
  - -1001593586990
  offset: 578
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
