admins: []
forwards:
- source: -1001791537277
  dest:
  - -1001778130057
  offset: 382
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
